<?php

/**
 * @file
 * Provides additional Git-specific integration between the Version Control API
 * suite and the Project suite.
 */

/**
 * Implements hook_menu().
 */
function versioncontrol_project_git_menu() {
  $items['node/%project_node/edit/default-branch'] = array(
    'title' => 'Default branch',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('versioncontrol_project_git_default_branch_form', 1),
    'access callback' => 'versioncontrol_project_git_default_branch_access',
    'access arguments' =>  array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
    'file' => 'versioncontrol_project_git.pages.inc',
  );

  return $items;
}

/**
 * Access callback: Checks for a user's access to a valid Git repository.
 *
 * Path: node/%project_node/edit/default-branch
 *
 * @param $project
 *   The project object that should have an attached repository.
 *
 * @return
 *   TRUE if the project has an attached Git repository with at least one
 *   branch that the user has write access to, FALSE otherwise.
 *
 * @see versioncontrol_project_git_menu()
 */
function versioncontrol_project_git_default_branch_access($project) {
  // Display only on nodes that have a repository attached.
  if (empty($project->versioncontrol_project)) {
    return FALSE;
  }

  // Ensure it is a Git repository.
  $repo = $project->versioncontrol_project['repo'];
  if (!$repo instanceof VersioncontrolGitRepository) {
    return FALSE;
  }

  // Ensure at least one branch exists.
  if (!count($repo->loadBranches())) {
    return FALSE;
  }

  // Check the permissions.
  return project_user_access($project, 'write to vcs');
}
